name: Scala CI

on:
  push:
    branches: ["developer"]
  pull_request:
    branches: ["developer"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up sbt
        run: |
          echo "Setting up sbt"
          mkdir -p $HOME/.sbt
          curl -sL https://github.com/sbt/sbt/releases/download/v1.8.2/sbt-1.8.2.tgz | tar xz -C $HOME/.sbt
          export PATH=$HOME/.sbt/bin:$PATH
          sbt --version
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: compile
        run: sbt compile

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Project and export Coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          export CI_BRANCH="${GITHUB_REF#refs/heads/}"
          sbt clean jacoco jacocoCoveralls
