name: Scala CI

on:
  push:
    branches: [ "main", "developer" ]
  pull_request:
    branches: [ "main", "developer" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up sbt
        uses: sbt/setup-sbt@v1

      - name: compile
        run: sbt clean compile

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up sbt
        uses: sbt/setup-sbt@v1

      - name: Build Project and Run Tests
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sbt "; project util; +clean; +coverage; +test; +coverageReport"
          sbt "; project core; +clean; +coverage; +test; +coverageReport"
          sbt "; project model; +clean; +coverage; +test; +coverageReport"
          sbt "; project computer; +clean; +coverage; +test; +coverageReport"
          sbt "; project persistence; +clean; +coverage; +test; +coverageReport"

      - name: Export Coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run : |
          sbt "; project util; coverageAggregate; coveralls"
          sbt "; project core; coverageAggregate; coveralls"
          sbt "; project model; coverageAggregate; coveralls"
          sbt "; project computer; coverageAggregate; coveralls"
          sbt "; project persistence; coverageAggregate; coveralls"

  refresh_badge:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Refresh coverage badge
        uses: fjogeleit/http-request-action@master
        with:
          url: https://camo.githubusercontent.com/12c4fcb3b21fbb2a725fc61449fb1b91e972c4c8a2baaf5904936d8e334bdbe8/68747470733a2f2f636f766572616c6c732e696f2f7265706f732f6769746875622f62336230302f63736c792f62616467652e7376673f6272616e63683d64657626736572766963653d676974687562
          method: PURGE
